services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_scripts
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - postgres
      - kafka
      - minio
    restart: on-failure

  postgres:
    image: postgres:17.4
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: wpbd
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_WAL_LEVEL: logical
    ports:
      - "${POSTGRES_PORT}:5432"
    command: [
      "postgres",
      "-c", "wal_level=logical",
      "-c", "max_replication_slots=5",
      "-c", "max_wal_senders=5"
    ]

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_broker
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"    # external clients (host)
      - "9092:9092"                      # internal Docker services
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:9092,PLAINTEXT://0.0.0.0:${KAFKA_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:9092,PLAINTEXT://localhost:${KAFKA_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  debezium:
    image: debezium/connect:2.4
    container_name: debezium
    restart: always
    depends_on:
      - kafka
      - postgres
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: debezium_group
      CONFIG_STORAGE_TOPIC: debezium_configs
      OFFSET_STORAGE_TOPIC: debezium_offsets
      STATUS_STORAGE_TOPIC: debezium_status
    ports:
      - "8083:8083"

  debezium-configurator:
    image: curlimages/curl:latest
    container_name: debezium_configurator
    depends_on:
      - debezium
    volumes:
      - ./debezium:/config
    entrypoint: >
      sh -c "echo 'Waiting for Debezium...'; sleep 20; curl -X POST http://debezium:8083/connectors -H 'Content-Type: application/json' -d @/config/config.json"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    restart: always
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  spark:
    image: bitnami/spark:3.3.0
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_WEBUI_PORT=18080
    ports:
      - "7077:7077"
      - "18080:18080"
    depends_on:
      - kafka

  spark-job:
    image: bitnami/spark:3.3.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-job
    volumes:
      - ./spark:/app/spark
    depends_on:
      - kafka
      - debezium
      - debezium-configurator
      - spark
    command: [
      "/opt/bitnami/spark/bin/spark-submit",
      "--master", "spark://spark:7077",
      "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0,org.apache.spark:spark-token-provider-kafka-0-10_2.12:3.3.0,io.delta:delta-core_2.12:2.3.0",
      "/app/spark/stream.py"
    ]
    environment:
      - MINIO_USER=admin
      - MINIO_PASSWORD=admin123
      - MINIO_PORT=9000

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"  # API
      - "9005:9001"  # Console UI
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

volumes:
  minio_data:
